CREATE USER ITEM IDENTIFIED BY ITEM;
GRANT ALL PRIVILEGES TO ITEM;
CREATE USER PRICING IDENTIFIED BY PRICING;
GRANT ALL PRIVILEGES TO PRICING;
CREATE USER PROMOTION IDENTIFIED BY PROMOTION;
GRANT ALL PRIVILEGES TO PROMOTION;

COMMIT;
