DROP TABLE "PROMOTION"."PA_ITEM";
CREATE TABLE "PROMOTION"."PA_ITEM" 
   ("ITEM_ID" NUMBER(*,0) NOT NULL ENABLE, 
	"ITEM_NAME" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	"ITEM_DESCRIPTION" VARCHAR2(1000 BYTE) NOT NULL ENABLE, 
	"BRAND_ID" NUMBER(*,0) NOT NULL ENABLE, 
	"BRAND_NAME" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	"CATEGORY_ID" NUMBER(*,0) NOT NULL ENABLE, 
	"CATEGORY_NAME" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	"PRICE_DATE" DATE, 
	"PRICE_VALUE" FLOAT(126)
	);

ALTER TABLE "PROMOTION"."PA_ITEM" ADD CONSTRAINT "ITEM_ID_PK" PRIMARY KEY ("ITEM_ID");
ALTER TABLE "PROMOTION"."PA_ITEM" ADD CONSTRAINT "ITEM_NAME_UK" UNIQUE ("ITEM_NAME");
ALTER TABLE "PROMOTION"."PA_ITEM" ENABLE CONSTRAINT "ITEM_ID_PK";
ALTER TABLE "PROMOTION"."PA_ITEM" ENABLE CONSTRAINT "ITEM_NAME_UK";

DROP TABLE "PRICING"."PR_PRICE";
CREATE TABLE "PRICING"."PR_PRICE" 
   ("ITEM_ID" NUMBER(*,0) NOT NULL ENABLE,
	"PRICE_DATE" DATE NOT NULL ENABLE, 
	"PRICE_VALUE" FLOAT(126) NOT NULL ENABLE
	);
ALTER TABLE "PRICING"."PR_PRICE" ADD CONSTRAINT "PR_PRICE_ID_PK" PRIMARY KEY ("ITEM_ID");
ALTER TABLE "PRICING"."PR_PRICE" ENABLE CONSTRAINT "PR_PRICE_ID_PK";

DROP TABLE "ITEM"."IC_CATEGORY";
CREATE TABLE "ITEM"."IC_CATEGORY" 
   ("CATEGORY_ID" NUMBER(*,0) NOT NULL ENABLE,
	"CATEGORY_NAME" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"CATEGORY_DESC" VARCHAR2(1000 BYTE)
	);
ALTER TABLE "ITEM"."IC_CATEGORY" ADD CONSTRAINT "CATEGORY_ID_PK" PRIMARY KEY ("CATEGORY_ID");
ALTER TABLE "ITEM"."IC_CATEGORY" ADD CONSTRAINT "CATEGORY_NAME_UK" UNIQUE ("CATEGORY_NAME");
ALTER TABLE "ITEM"."IC_CATEGORY" ENABLE CONSTRAINT "CATEGORY_ID_PK";
ALTER TABLE "ITEM"."IC_CATEGORY" ENABLE CONSTRAINT "CATEGORY_NAME_UK";

DROP SEQUENCE "ITEM"."IC_CATEGORY_SEQ";
CREATE SEQUENCE "ITEM"."IC_CATEGORY_SEQ" INCREMENT BY 1 MAXVALUE 9999999 MINVALUE 1 CACHE 20;

DROP TABLE "ITEM"."IC_BRAND";
CREATE TABLE "ITEM"."IC_BRAND" 
   ("BRAND_ID" NUMBER(*,0) NOT NULL ENABLE,
	"BRAND_NAME" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"BRAND_DESC" VARCHAR2(1000 BYTE)
	);
ALTER TABLE "ITEM"."IC_BRAND" ADD CONSTRAINT "BRAND_ID_PK" PRIMARY KEY ("BRAND_ID");
ALTER TABLE "ITEM"."IC_BRAND" ADD CONSTRAINT "BRAND_NAME_UK" UNIQUE ("BRAND_NAME");
ALTER TABLE "ITEM"."IC_BRAND" ENABLE CONSTRAINT "BRAND_ID_PK";
ALTER TABLE "ITEM"."IC_BRAND" ENABLE CONSTRAINT "BRAND_NAME_UK";

DROP SEQUENCE "ITEM"."BRAND_ID_SEQ";
CREATE SEQUENCE "ITEM"."BRAND_ID_SEQ" INCREMENT BY 1 MAXVALUE 9999999 MINVALUE 1 CACHE 20;

DROP TABLE "ITEM"."IC_ITEM";
CREATE TABLE "ITEM"."IC_ITEM" 
   ("ITEM_ID" NUMBER(*,0) NOT NULL ENABLE,
	"ITEM_NAME" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"ITEM_DESCRIPTION" VARCHAR2(1000 BYTE) NOT NULL ENABLE,
	"BRAND_ID" NUMBER(*,0) NOT NULL ENABLE,
	"CATEGORY_ID" NUMBER(*,0) NOT NULL ENABLE
	);
ALTER TABLE "ITEM"."IC_ITEM" ADD CONSTRAINT "ITEM_ID_PK" PRIMARY KEY ("ITEM_ID");
ALTER TABLE "ITEM"."IC_ITEM" ADD CONSTRAINT "ITEM_NAME_UK" UNIQUE ("ITEM_NAME");
ALTER TABLE "ITEM"."IC_ITEM" ENABLE CONSTRAINT "ITEM_ID_PK";
ALTER TABLE "ITEM"."IC_ITEM" ENABLE CONSTRAINT "ITEM_NAME_UK";

DROP SEQUENCE "ITEM"."ITEM_ID_SEQ";
CREATE SEQUENCE "ITEM"."ITEM_ID_SEQ" INCREMENT BY 1 MAXVALUE 9999999 MINVALUE 1000 CACHE 20;



/*CREATE FUNCTION "ITEM"."get_CATEGORY_ID" RETURN NUMBER IS
BEGIN
  RETURN "ITEM"."IC_CATEGORY_SEQ".nextval;
END;
CREATE FUNCTION "ITEM"."get_ITEM_ID" RETURN NUMBER IS
BEGIN
  RETURN "ITEM"."ITEM_ID_SEQ".nextval;
END;
CREATE FUNCTION "ITEM"."get_BRAND_ID" RETURN NUMBER IS
BEGIN
  RETURN "ITEM"."BRAND_ID_SEQ".nextval;
END;*/


COMMIT;
